name: "_shared"
ask: |
  Follow the guardrails and context. For every task:
  1) Produce plan.md.
  2) Generate minimal, clean diffs.
  3) Add/adjust tests.
  4) Provide HOW_TO_VERIFY.md (commands + expected outputs).
context:
  - path: .codex/context.md
  - path: .codex/guardrails.md
  - path: .codex/prompts/agent_roles.md
  - path: .codex/prompts/tool_contracts.md
  - path: Makefile
  - path: apps/
  - path: package.json
outputs:
  - plan.md
  - HOW_TO_VERIFY.md
  - FOLLOWUPS.md
run:
  - "Apply patch"
  - "Run: make test"
  - "Iterate until tests pass"