extends: "./_shared.yaml"
name: "M2 – MCP + Agentic Source Gathering (Explorer pipeline v1)"
ask: |
  Implement feature_spec at feature_specs/m2_mcp_agentic_gathering.md.
  Deliver:
  - Minimal MCP server exposing tools: search_web, fetch_page, expand_links, deduplicate_sources.
  - Lead Verifier agent calls Explorer subagent to gather N diverse sources respecting time window.
  - Persist sources as Evidence rows with metadata (title, url, published_at, retrieved_at, domain).
  - Basic deduplication + source diversity heuristics (domain spread).
  - Integrate with /claims/{slug}/verify pipeline BEFORE model calls.
  - Tests: tool-call smoke tests (mocked), evidence persistence, diversity threshold check.
inputs:
  - path: feature_specs/m2_mcp_agentic_gathering.md
outputs:
  - plan.md
  - HOW_TO_VERIFY.md
  - apps/adjudicator/**/*
  - mcp/**/*
  - tests/**/*
