extends: "./_shared.yaml"
name: "M4 – Replay Bundles (Per-Model, Downloadable)"
ask: |
  Implement feature_spec at feature_specs/m4_replay_bundle.md.
  Deliver:
  - Trace recorder that captures: timestamps, tool calls, prompts, responses, decisions, evidence IDs.
  - Store a per-model replay JSON linked to Verification ID; redactions applied.
  - Export endpoint: /verifications/{id}/replay?model=provider_id -> returns zip (JSON + pretty HTML).
  - UI: “View Trace” modal and “Download Bundle” button per model.
  - Tests: trace completeness, redaction of secrets, deterministic hashing of replay.
inputs:
  - path: feature_specs/m4_replay_bundle.md
outputs:
  - plan.md
  - HOW_TO_VERIFY.md
  - apps/adjudicator/**/*
  - apps/web/**/*
  - tests/**/*
