name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  backend-python:
    name: Backend (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        working-directory: apps/adjudicator
        run: |
          if [ -f pyproject.toml ]; then pip install -e .; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # optional: if you rely on repo root requirements
          if [ -f ../../requirements.txt ]; then pip install -r ../../requirements.txt; fi

      - name: Run tests
        working-directory: apps/adjudicator
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q
          elif [ -f ../../Makefile ]; then
            make -C ../../ test
          else
            echo "No pytest/Makefile found" && exit 1
          fi

  frontend-web:
    name: Frontend (build + tests)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/web/package-lock.json

      - name: Install
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Test
        run: |
          if npm run | grep -q " test"; then
            npm test --if-present -- --ci --reporters=default
          else
            echo "No frontend tests defined (npm test). Skipping."
          fi

      - name: Build
        run: |
          npm run build --if-present
